# SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
# SPDX-License-Identifier: Apache-2.0

processor:
  ignoreTypes:
    - "(EgressIP|EgressQoS|EgressFirewall|EgressService|AdminPolicyBasedExternalRoute)List$"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.28
